WebServer:
  image: nginx
  ports:
    - "8080:80"
  volumes:
    - /home/nigam/Nigam_DevOps/Nigam_Docker/webserver-tomcat-cluster/default.conf:/etc/nginx/conf.d/default.conf
  links:
    - tomcatOne:tomcat1
    - tomcatTwo:tomcat2
    - tomcatThree:tomcat3
tomcatOne:
  image: tomcat
  volumes:
    - /home/nigam/Nigam_DevOps/Nigam_Docker/webserver-tomcat-cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - /home/nigam/Nigam_DevOps/Nigam_Docker/webserver-tomcat-cluster/server.xml:/usr/local/tomcat/conf/server.xml
    - /home/nigam/Nigam_DevOps/Nigam_Docker/webserver-tomcat-cluster/ROOT:/usr/local/tomcat/webapps/ROOT
tomcatTwo:
  image: tomcat
  volumes:
    - /home/nigam/Nigam_DevOps/Nigam_Docker/webserver-tomcat-cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - /home/nigam/Nigam_DevOps/Nigam_Docker/webserver-tomcat-cluster/server.xml:/usr/local/tomcat/conf/server.xml
    - /home/nigam/Nigam_DevOps/Nigam_Docker/webserver-tomcat-cluster/ROOT:/usr/local/tomcat/webapps/ROOT
tomcatThree:
  image: tomcat
  volumes:
    - /home/nigam/Nigam_DevOps/Nigam_Docker/webserver-tomcat-cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - /home/nigam/Nigam_DevOps/Nigam_Docker/webserver-tomcat-cluster/server.xml:/usr/local/tomcat/conf/server.xml
    - /home/nigam/Nigam_DevOps/Nigam_Docker/webserver-tomcat-cluster/ROOT:/usr/local/tomcat/webapps/ROOT
