# To Bring up the container mentioned in this yml file
# docker-compose -f <Docker-Compose-File-Name> up -d
# docker-compose -f Docker-Compose_CICD.yml up -d

# To Bring down the container mentioned in this yml file
# docker-compose -f <Docker-Compose-File-Name> down
# docker-compose -f Docker-Compose_CICD.yml down

version: "3.2"
#ARG buildno
#RUN echo "Build number: $buildno"
# ========================================================================================
services:
  web_server:
    image: nginx:alpine
    ports:
      - "8083:80"
#    volumes:
#      - ${PWD}/Tomcat_Cluster/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app_server:server
#    links:
#      - TomcatServer1:server1
#      - TomcatServer2:server2
#      - TomcatServer3:server3
    networks:
         - network1
# ---------------------------------------------------------------------------------------
  app_server:
    image: tomcat
    hostname: TomcatServer
    container_name: TomcatServer
    depends_on:
      - db_server
#    command: bundle exec thin -p 3000
    volumes:
      - ${PWD}/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ${PWD}/server.xml:/usr/local/tomcat/conf/server.xml
      - ${PWD}/NigamTestApp1.war:/usr/local/tomcat/webapps/NigamTestApp1.war
    links:
      - db_server
    networks:
         - network1
         - network2
# ---------------------------------------------------------------------------------------
  db_server:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpW
      MYSQL_DATABASE: dbapp1
      MYSQL_USER: app1
      MYSQL_PASSWORD: app1
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
         - network2
# ========================================================================================
networks:
  network1:
  network2:

volumes:
  mydata:
  mysql-data:
